name: Open Issue Metrics - artifact
on:
  workflow_dispatch:
#  schedule:
#    - cron: '3 2 1 * *'

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v3
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:Qiskit/qiskit is:issue is:open'
        HIDE_AUTHOR: true
        HIDE_TIME_TO_CLOSE: true
        HIDE_TIME_TO_ANSWER: true


    - name: Archive issue metrics report
      uses: actions/upload-artifact@v4
      with:
        name: issue-metrics-report
        path: ./issue_metrics.md
          

